### ISSUE TITLE
Any way to remove the limitation on '#' characters in strings?

### ISSUE THREAD

**Issue by EricBrunel** [QQuick/Opy#10]
Hello,

I'm trying to use Opy on a rather large project and so far, it's the best available solution I've found. But I find the limitation about '#' characters that can only appear at the beginning of a string to be really annoying. There are a lot of such strings in the code I'm trying to obfuscate, and the project is a living one, so we'll have to remember to format all strings correctly or the obfuscation won't work. I also noticed that even if strings are not obfuscated, the limitation applies anyway, and a string containing a '#' not in the first position will cause invalid code to be generated.
Is there any chance that this limitation will go away one day? And also, would it be at least possible to detect the 'bad' string and make the obfuscation fail, instead of generating wrong code? On large projects, the full obfuscation can last for quite some time; finding out in the end that the results are unusable because we've forgotten a string containing a '#' somewhere is quite frustrating…

Thanks!

**Comment by JdeH** [comment]
Hi,

The # limitation is a consequence of Opy not truely parsing Python, but rather loosely analysing it. The upside is that Opy doesn't depend on Python versions. The downside is this type of limitation.

I wasn't too pleased with these limitations myself, so I gave it quite some thoughts. The problem is that # may occur in multi-line strings, and that """, ''', " and ' can be nested. On top of that, all these quotes can also occur in comments.  If this were easily detectable, well, the problem would be half solved...

So unfortunately I have no out of the box solution for this, it's embedded deeply in the somewhat hackish nature of Opy. Some kind of state machine reading through the source would probably be the best solution. Currently I am rather occupied with Transcrypt, so there's no immediate outlook upon a solution.

Kind regards
Jacques

**Comment by EricBrunel** [comment]
Thanks for your answer. I kind of guessed it wasn't easy, or I guess it would have been done already…
I've actually found some kind of workaround for the issue: I was also looking for a way to remove all docstrings from the code before feeding it to Opy. I've found a tool called pyminifier for that - that actually does obfuscation too, but not as good as Opy IMHO -, and since it parses the code using the 'tokenize' module, it's been reasonably easy to hack it to also make it split the strings containing a '#' character that isn't at the first position. I'll make sure everything works correctly and suggest to reintegrate my modifications in pyminifier, for example via a new specific option for source code preparation for Opy.

**Comment by JdeH** [comment]
That's a nice trick!
I've considered using tokenize as part of Opy, but I wasn't sure it will be Python version independent. As a separate preprocessing stage to only deal with strings it makes sense. Moreover if you use the tokenizer of the Python version you're working with, you'll always have the right one.

**Comment by andimarafioti** [comment]
Does this problem comes from line 229 of opy.py?:

`commentRegEx = re.compile (r'{0}{1}{2}.*?$'.format ( r"(?<!')", r'(?<!")', r'#' ), re.MULTILINE)`

If so, shouldn't an slightly more powerful regEx fix it?

**Comment by JdeH** [comment]
Hi,

@EricBrunel, the enhancement of @andimarafioti has been pulled and made optional.
I guess it should solve some of the problems for code conforming PEP8.
Only <blank>#<blank><blank> now cannot occur inside strings.

Kind regards
Jacques
