### ISSUE TITLE
Can't separate external dependencies from project modules

### ISSUE THREAD

**Issue by sergei-sh** [QQuick/Opy#9]
Hi there, your project is definetely useful, especially because it allows for obfuscation of module names.

 I've spent few hours trying to make your program work with my (not too big) project, but gave up at the end. The problem is that I have to blacklist all external module names found like the following:

import module1
from module1 import class1
import module1.class2 
... etc

After a lot of grepping and manual selection I succeeded, but found that the following also doesn't work:

from name1 import name2
name2.method()

Although blacklisting name1 and name2, method() is being obfuscated and thus does not work. I don't see an easy automated way to collect all those method()s

a) I think you could add automatic detection of project modules (not too difficult AFAIU) and exclude all external modules/namespaces from obfuscation.

b) Another solution is to obfuscate only those symbols which are NOT modules and o. modules by whitelist. Getting a whitelist of (project) modules is an easy task, even if done manually

**Comment by JdeH** [comment]
Indeed in the case:

`from name1 import name2`

the blacklist should contain

`name1.name2`

as well.

This blacklisting is quite labor-intensive and error prone. Still for a multiyear project for me it was doable, and once it was done, I didn't have to invest much energy in it anymore.

I think your proposal under a) is a very good approach, so:

- Find out which modules are part of the project and remember them in a set
- Skim through all imports and find out which imported modules are not in that set
- Exclude every name they export from obfuscation.

A problematic point is that Opy, since it want to be version independent, doesn't really parse Python.
It just uses regexes to find identifiers.

Still I guess with some clever tricks imports should be detectable with reasonable reliabiliy.
Finding out which modules are part of the project will also not be completely watertight, since paths may play a role, but with some simplifications it should be doable also with reasonable reliability.

Still testing and getting out all the minor pitfalls will cost some time.
Currently I am rather tied up in the Transcrypt project and I am not sure I'll find the time anytime soon, but I'll keep your idea in mind as an improvement to Opy, it certainly is a good idea.

Kind regards
Jacques

**Comment by sergei-sh** [comment]
You're right in the first case I actually didn't blacklist the right identifier.
But after succeding with dependencies, I've found inconsistencies with internal imports.

**Comment by wuyj88** [comment]
How about this case:

From name1 import *

Any way to deal with that? Or I have to change it to multiple lines for each item imported from name1?

Thanks.

**Comment by JdeH** [comment]
Does it work now?
If not, could you tell my which inconsistencies exactly.
A minimal complete example that shows this problem would help.

KR
Jacques

**Comment by JdeH** [comment]
No feedback received.
I'll close this for now.
Feel free to reopen.
